name: Deploy to GitHub Pages

on:
  push:
    branches: [main, staging]
  workflow_dispatch: # Allow manual deployment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v5
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        # Set custom domain based on branch
        cname: ${{ github.ref == 'refs/heads/main' && 'bingo.string.sg' || 'staging.bingo.string.sg' }}
        # Enable force orphan for clean history
        force_orphan: true
        # Add commit info
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        commit_message: ${{ github.event.head_commit.message }}